language: ruby
rvm:
- 2.5.1
deploy:
  api_key:
    secure: t92Dqh7345+qjEV6Y2jVP/bzhgch2yDGr0KGtRpUSFPN1LTmfzf60CzNZNmFrXKM13xe4bJAOGcNnRBYjaOsJNyD6hrkYLJtGIzFqoc3EHuPElU4Vuc0aXw9DEV751SGyntp3sCcETDZRhU2iGW/5Us18juZKfsSxaEOzp/6eMD3qhJAJOuKxibRvvERZfQ0IQTMH/Mej8HNeuaGZ4MawCi6A/BNZhccpawGutE46gF3frbU6h32ZrLj9x8RHs5VsnHLGzMkWvHRHBQXCMhE3NCnHzJ41AfsPtdzmFKL10SVn/5bnZT4rHDVe/iHdkQ7sI+2boo5PiLhZigBRVmbTz4wY/sIJNccsVWZQ2FSmRRWx4/R/tATs53vsocKnM4f37uMpGs2IvQEcR4k+qRHqx4bWiEV9h5Khlu6dMN3TFLWa8N5D6UKQYg5+BqzM3tVy3Y08ERmUHexfEwCSInMt8hFqtXoTpPCV/yChiyZTGPEaGr+XP3uDvqyssdHC+xzKEgiWbW3Na3SJV6FB45N/ttXBSZI2TXCSIfUnf0ZhH5EN7rlMZWPlvDKRq9KaALImXkIqVr+k5Y6V8ENmKAaCnptCFimT+00W9C0o8nSjS0exdlRUPojKoEegV0rml9AP0KhqNWCTz/UJgrMh1mSHT/LkoisL5+bMtqZJe0NoeY=
