development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  host: <%= ENV["REDISCLOUD_HOST"] %>
  user: <%= ENV["REDISCLOUD_USER"] %>
  url: <%= ENV["REDISCLOUD_URL"] %>
  password: <%= ENV["REDISCLOUD_PASSWORD"] %>
  port: 10679
  channel_prefix: how_are_you_today_production
